# Generated by Django 4.2.18 on 2026-02-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('crop', models.CharField(max_length=100)),
                ('land_size_acres', models.FloatField()),
                ('soil_type', models.CharField(max_length=50)),
                ('irrigation', models.CharField(max_length=10)),
                ('investment_capacity', models.FloatField()),
                ('suitability_score', models.FloatField(null=True)),
                ('net_profit', models.FloatField(null=True)),
                ('roi', models.FloatField(null=True)),
                ('farmer_emotion', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Analysis Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
